blueprint:
  name: ZHA - Ecodim 1, Channel remote
  description: |
    Control anything using the Ecodim remote

  domain: automation
  input:
    remote:
      name: Remote controller
      description: Remote to use
      selector:
        device:
          integration: zha
          manufacturer: EcoDim
          model: ED-10010
    button_on:
      name: On Button
      description: Action to run on press on On button
      default: []
      selector:
        action:
    button_on_long:
      name: On Long Press
      description: Action to run on press on On long button
      default: []
      selector:
        action:
    button_off:
      name: Off Button
      description: Action to run on press on Off button
      default: []
      selector:
        action:
    button_off_long:
      name: Off Long Press
      description: Action to run on press on Off long button
      default: []
      selector:
        action:
    
mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - variables:
      event: "{{ trigger.event.data.event }}"
  - choose:
      - conditions:
          - "{{ event == 2001 }}"
        sequence: !input button_off_long
      - conditions:
          - "{{ event == 2002 }}"
        sequence: !input button_off
      - conditions:
          - "{{ event == 1001 }}"
        sequence: !input button_on_long
      - conditions:
          - "{{ event == 1002 }}"
        sequence: !input button_on